### ISSUE TITLE
Badge icon for doc count

### ISSUE THREAD

**Issue by chriszarate** [mlaa/buddypress-docs#1]
Add badge icon similar to that of "Files" and "Members."

**Comment by terrainsvagues** [comment]
Definitely let's fix this! I was just working with Terry on something and we couldn't find docs he knew had been uploaded. And this bug is why.

**Comment by JonathanReeve** [comment]
This corresponds to the upstream bug boonebgorges/buddypress-docs#423.

**Comment by JonathanReeve** [comment]
@terrainsvagues also suggests a color change in this badge for doc changes.

**Comment by JonathanReeve** [comment]
Let's definitely talk about this during the next meeting.

**Comment by JonathanReeve** [comment]
Possibly related: https://buddypress.org/support/topic/doc-counter-not-updating-properly-order-wonky/

**Comment by JonathanReeve** [comment]
See also boonebgorges/buddypress-docs#261. 
This was a feature, albeit a hacky one, but was disabled at boonebgorges/buddypress-docs@8c636605586df477db4289eeff70d0a0271bed3b. Also see [comments on the function](https://github.com/boonebgorges/buddypress-docs/blob/8c636605586df477db4289eeff70d0a0271bed3b/includes/integration-groups.php#L661) itself.

**Comment by JonathanReeve** [comment]
This was so easy to fix that I'm worried that it will cause unexpected behavior. There are warnings in the comments about this function being broken, so I'm convinced that I'm just not seeing the broken part--the reason why this function was disabled in the first place.

**Comment by JonathanReeve** [comment]
Here's what was happening: 
 * `update_doc_count()` wasn't working, because it relies on using `bp_is_group` to check whether we're creating or deleting a group document, and `bp_is_group` returned 0, because, judging from the slug at `/docs`, bp didn't know that we were in a group context. 
 * it's possible that the hooks for `update_doc_count()` weren't working, since they were hooked in using `add_filter` instead of `add_action`, and the hooks `bp_docs_doc_saved` and `bp_docs_doc_deleted` appear to be action hooks instead of filter hooks.

**Comment by JonathanReeve** [comment]
Ok, so if we can live with this: 

![selection_505](https://cloud.githubusercontent.com/assets/1843676/6401492/deba0990-bdce-11e4-8d7f-ec9265d4ad8b.png)

then doc count badges should be working.
